### ISSUE TITLE
What is the use of vgg_face_descriptor.predict(real_images)**[0,:]** 

### ISSUE THREAD

**Issue by praveenkumarchandaliya** [serengil/tensorflow-101#10]
img1_representation = vgg_face_descriptor.predict(real_images)**[0,:]**  what is the use of [0,:] meaning, can you explain what is use of this[0,:]

**Comment by serengil** [comment]
predict function append one dummy dimension. VGG normally returns 2622 dimensional vector as output but predict function will return (1, 2622). You should print the shape of that line to understand.

`vgg_face_descriptor.predict(real_images).shape`
