### ISSUE TITLE
Pandas-vs-Modin.ipynb example csv files not found

### ISSUE THREAD

**Issue by miguelusque** [serengil/tensorflow-101#12]
Hi @serengil ,

I am trying to reproduce your tests about Pandas vs Modin, but unfortunately, I cannot find the different csv files used in that notebook.

Could you please upload them somewhere?

Thank you!!!

Regards,
Miguel

**Comment by serengil** [comment]
Please read this tutorial: https://sefiks.com/2019/04/23/how-modin-can-keep-data-scientists-from-pandas/

It will guide you to the source links
