### ISSUE TITLE
vgg-face.ipynb how to evaluate on a dataset

### ISSUE THREAD

**Issue by dingusagar** [serengil/tensorflow-101#16]
Could you share the script to do the evaluation of the model on dataset. My doubt is in order to find the accuracy on a dataset, do we take every pair of embedding in the dataset and check if the model can correctly detect as the same person or not? Or is there some other standard approach to evaluate the face recongition models which are designed in one shot learning fashion?

**Comment by serengil** [comment]
I'm going to share but this is not an issue. That's why, it is closed.

**Comment by dingusagar** [comment]
Ok thanks. Would be really helpful if you could share it
