### ISSUE TITLE
why only detect the faces? Not recognize.

### ISSUE THREAD

**Issue by TasilNimashan** [serengil/tensorflow-101#18]
Brother, I used your real-time face recognition of the deep face. Its working fine but it only detects the faces not recognise the faces via my database like your video? Give me a solution brother.

**Comment by serengil** [comment]
you cropped the faces in your database? it might be related to your web cam's resolution.

**Comment by TasilNimashan** [comment]
Yes, I input the two face images of peoples to the database. I also think it is an issue of webcam. It is not clear like yours. Can you give some solution for this? Brother how to connect my mobile phone camera for this?

**Comment by serengil** [comment]
how to connect my mobile phone camera for this? -> I really don't know
