### ISSUE TITLE
age-gender-prediction-real-time.py

### ISSUE THREAD

**Issue by vooncc** [serengil/tensorflow-101#22]
When I run your above program, I encountered below messages. 
 [ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-vi271kac\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Thank you

**Comment by serengil** [comment]
your opencv installation seems not oke.
