### ISSUE TITLE
Using DeepFace on a Database

### ISSUE THREAD

**Issue by CrimsonMiralis** [serengil/tensorflow-101#23]
Wasn't sure where else to ask this so I made an issue here since it has the source code of this article, 
Is there a way to use your deepface library to get the gender, age, and ethnicity estimations from each person in the database?
https://sefiks.com/2021/02/06/deep-face-recognition-with-sql/?unapproved=3034&moderation-hash=f5f6fc54c7e8ebd2af7f1bd3d1283caa

**Comment by serengil** [comment]
Actually, I explained how to that in the tutorial you shared.
