### ISSUE TITLE
Pre-trained weights of SphereFace

### ISSUE THREAD

**Issue by HamDan1999** [serengil/tensorflow-101#28]
Hi,
Could you please provide the pre-trained weights that you used in your SphereFace tutorial?
Their link (Weights: https://drive.google.com/open?id=0B_geeR2lTMegb2F6dmlmOXhWaVk) requires permission and they are not responding to the permission request.

**Comment by serengil** [comment]
Firstly, this is not my model. I used the weights in the reference study.

Secondly, I can access this file right now: https://drive.google.com/file/d/0B_geeR2lTMegb2F6dmlmOXhWaVk/view?resourcekey=0-q8b8x8BkzLz-kotTIB0UoQ
