### ISSUE TITLE
Adding custom GUI for emotion labels

### ISSUE THREAD

**Issue by Kingbadger3d** [serengil/tensorflow-101#5]
Hi Serengil, Ive loved your tutorials and have been very helpfull to me in my learning, I was woundering if you could share an exmple of how you added the custom label background in grey that shows all the emotion detection states with percentanges on the zuckerberg example image, In the demo code you just get the emotion writen above the bounding box. This would really help me out as cant find any info on custom GUI outputs with opencv and AI platforms. Cheers J

**Comment by serengil** [comment]
Hello, Thank you for your feedback. I realize that mood analysis code for stream is duplicated. You can find the code you need is [here](https://github.com/serengil/tensorflow-101/blob/master/python/emotion-analysis-from-video.py). Basicallyi the following code block handles the transparent grey area. I also update the read-me file with this link. Do not hesitate to contact if you have any trouble.
