### ISSUE TITLE
How to train network for custom dataset?

### ISSUE THREAD

**Issue by jcgarciaca** [serengil/tensorflow-101#8]
I've used your pre-trained weights for face recognition and it seems to work well. Thank you.
Now, I am interested to use a similar network to verify if two images match or not (no faces). Do you have any idea about how could I train my network?

In your code for face recognition, an image is used as input for network and a vector is generated as output. Both images (faces) are fed to network such that -both- generated vectors are then compared with cosine or euclidean similarity. 

But in my case I just have two images that match or not.

**Comment by serengil** [comment]
You should study Siamese Network. This face recognition model is trained by its procedures.

**Comment by serengil** [comment]
This is not an issue. This is closed.
