### ISSUE TITLE
Not actually an issue, need in detail what needs to be done on deep face recognization

### ISSUE THREAD

**Issue by KrishnaThali** [serengil/tensorflow-101#9]
I am new to this field, and in need to learn more. Can you please provide me detail steps what needs to be done and how this has to be followed?

**Comment by serengil** [comment]
The following documents will help you to understand this concept

1- VGG-Face, https://sefiks.com/2018/08/06/deep-face-recognition-with-keras/

2- FaceNet, https://sefiks.com/2018/09/03/face-recognition-with-facenet-in-keras/

Also follow the links in the blog posts.

**Comment by serengil** [comment]
Closed due to not an issue
